software_version = {
        'software_version':'',
        'show run': """ """,
        'show version': """ """,
        'show int status': """ """,
        'show run | section interface': """ """,
        'show run | in interface': """ """,
        'show interface link': """ """,
        'show interface': """ """,
        'show inventory': """ """,
        'show interface counters': """ """,
        'show cdp nei detail': """ """,
        'show module all': """ """,
        'show module': """ """,
        'show run | section snmp': """ """,
        'show run | in snmp': """ """,
        'show snmp user': """ """,
        'show access-list': """ """,
        'show run | section logging': """ """,
        'show run | in logging': """ """,
        'show mac address-table': """ """,
        'show run | section tacacs': """ """,
        'show run | in tacacs': """ """,
        'show power inline': """ """,
        'show environment all': """ """
    }
router_software_version = {
        'software_version':'',
        'show run | inc hostname': """ """,
        'show run | section in Vlan': """ """,
        'show run | section in Ethernet': """ """,
        'show run | section interface Vlan': """ """,
        'show run | section Vlan': """ """,
        'show run | section interface | section Ethernet': """ """,
        'show run | section interface | section port-channel': """ """,
        'show inventory': """ """,
        'show interface counters': """ """,
        'show cdp nei detail': """ """,
        'show module': """ """
    }