services:
  frontend:
    image: alpine:3.19.0
    ports:
      - "443:8043"
    networks:
      - front-tier
      - back-tier
    configs:
      - httpd-config
    secrets:
      - server-certificate

  backend:
    image: mysql
    volumes:
      - db-data:/etc/data
    networks:
      - back-tier

volumes:
  myapp:

configs:
  httpd-config:
    external: true

secrets:
  server-certificate:
    external: true

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}